### ISSUE TITLE
Slim image fails to start if an update to steamcmd exists

### ISSUE THREAD

**Issue by arseneyr** [YanWenKun/barotrauma-server-docker#2]
If an update to `steamcmd` exists since the last `slim` docker image was pushed to Docker Hub, the server will fail to start. For example, using the digest for the latest `slim` image:
```
docker run --rm yanwk/barotrauma-server@sha256:5611317814f2e15df9eefa515d9e4819f5eb361e61df38e4d3677c777b10906e
Redirecting stderr to '/home/runner/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (182 of 57,751 KB)...
<SNIP>
[ 99%] Downloading update (57,751 of 57,751 KB)...
[100%] Download complete.
[user ~]$
```
I believe this is a result of the update requiring root privileges, although `steamcmd` is not very verbose about it. A simple fix would be to include `&& steamcmd +quit` in the Dockerfile `CMD` before doing `su runner`. A more involved solution would be to install `steamcmd` as the non-root user, but that seems like a lot of work.

**Comment by YanWenKun** [comment]
Thank you!
That's a good idea. I'm on the way testing. It's better than asking people to `docker pull` a new image :-)
