### ISSUE TITLE
Can't get mods to load (using `slim`)

### ISSUE THREAD

**Issue by arousle** [YanWenKun/barotrauma-server-docker#5]
Hi. This issue is basically a cross-post [of the issue I made on the Barotrauma repo](https://github.com/Regalis11/Barotrauma/issues/11855), since I'm not sure if this is an issue with the Docker image or the dedicated server executable itself. In short, the problem is that content packages specified in the `user_config.xml` aren't being loaded by the server at launch — but please see the linked issue for the full description of the problem.

I'm using the `slim` variant of the Docker image, using `docker compose` to launch it.

If someone using this Docker image to host a dedicated server with mods enabled could share their full `user_config.xml` so I can compare it with mine, that'd be a useful next step to investigate the issue, I think.

Thanks in advance for any help! 🙏

**Comment by YanWenKun** [comment]
Thanks for the information and sorry for being slow to respond. 🙏
I just read the whole [issue](https://github.com/Regalis11/Barotrauma/issues/11855) and it reminds me of another [issue](https://github.com/Regalis11/Barotrauma/issues/10112) which only occurs on Linux.
A nice PR (#3, btw he uses Workshop mods) have fixed this and `slim` start script have changed. In short, made a nesting symlink:

```
mkdir -p "${GAMEDIR}/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH"

ln -s \
    "${GAMEDIR}/Daedalic Entertainment GmbH/Barotrauma" \
    "${GAMEDIR}/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma"
```

Hope this can help 👀
